DROP DATABASE IF EXISTS job_application_db;
CREATE DATABASE job_application_db;

USE job_application_db;

CREATE TABLE IF NOT EXISTS applications (
    application_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    summary VARCHAR(512),
    application_link VARCHAR(512),
    date_sent VARCHAR(50),
    elapsed_time INT,
    status VARCHAR(100),
    interview_status VARCHAR(100),
    email VARCHAR(255)
);

INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Staff, Software Engineer', 'Walmart', 'https://careers.walmart.com/us/en/jobs/R-2211510', 'https://careers.walmart.com/us/en/candidate-home/applications/f556c351-7317-4d59-a312-67e6b6a7e9e0/details', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Intern, Software Engineering', 'Braze', 'Summary & App Link', '', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Programmer Intern', 'Acuity Insurance', 'Summary & App Link', '', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineering Intern', 'Datadog', 'https://careers.datadoghq.com/detail/7367016/?gh_jid=7367016&gh_src=8363eca61', '', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Java Software Engineer', 'BeaconFire Solution Inc.', 'https://www.linkedin.com/jobs/collections/it-services-and-it-consulting/?currentJobId=4266998367&discover=recommended&discoveryOrigin=JOBS_HOME_JYMBII', '', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Developer', 'United University', 'https://www.linkedin.com/jobs/view/4312154956', '', '12/1/2025', '8', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Development Intern', 'Altanova', 'https://www.linkedin.com/jobs/view/4340769102', '', '12/2/2025', '7', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineering Intern', 'MongoDB', 'https://www.mongodb.com/careers/jobs/7335932', '', '12/2/2025', '7', 'DENIED', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineering Intern', 'GPTZero', 'https://www.linkedin.com/jobs/view/4348156838', '', '12/2/2025', '7', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Intern', 'Premier Early Childhood Education Partners', 'https://www.linkedin.com/jobs/view/4341036844', '', '12/2/2025', '7', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Intern', 'Wakefern Food Corp.', 'https://www.linkedin.com/jobs/view/4348257065', '', '12/2/2025', '7', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Intern', 'Plug and Play Tech Center', 'https://www.linkedin.com/jobs/view/4325417206', '', '12/2/2025', '7', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Information Technology Summer Intern', 'ParetoHealth', 'https://www.linkedin.com/jobs/view/4321871163', '', '12/2/2025', '7', 'DENIED', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Support Technician', 'Inceed', 'https://www.linkedin.com/jobs/view/4325475581', '', '12/3/2025', '6', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Admin', 'Palo Alto Networks', 'https://www.linkedin.com/jobs/view/4341525771', '', '12/3/2025', '6', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Entry-Level Helpdesk Technician', 'Pathway Technologies, Inc.', 'https://www.linkedin.com/jobs/view/4341551692', '', '12/3/2025', '6', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('IT Technician', 'Inceed', 'https://www.linkedin.com/jobs/view/4325067648', '', '12/3/2025', '6', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Desktop Support Technician', 'COGENT Infotech', 'https://www.linkedin.com/jobs/view/4341033779', '', '12/3/2025', '6', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Co-op Software Engineer', 'Rockwell Automation', 'https://rockwellautomation.wd1.myworkdayjobs.com/en-US/External_Rockwell_Automation/job/Co-op--Software-Engineer_R25-8315', 'https://rockwellautomation.wd1.myworkdayjobs.com/en-US/External_Rockwell_Automation/userHome', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software developer (API) - Fiix', 'Rockwell Automation', 'https://rockwellautomation.wd1.myworkdayjobs.com/en-US/External_Rockwell_Automation/job/Toronto-Ontario-Canada/Software-developer--API----Fiix_R25-7455?q=Software', 'https://rockwellautomation.wd1.myworkdayjobs.com/en-US/External_Rockwell_Automation/userHome', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Web Application Developer', 'CapFront', 'https://www.linkedin.com/jobs/view/4315239596', '', '12/4/2025', '5', 'DENIED', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Information Technology Intern', 'AMOREPACIFIC', 'https://www.linkedin.com/jobs/view/4319153014', '', '12/4/2025', '5', 'DENIED', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Java Full Stack Developer', 'BeaconFire Solution Inc.', 'https://www.linkedin.com/jobs/view/4303408125', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Web Developer', 'Synechron', 'https://www.linkedin.com/jobs/view/4341124113', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Development Intern', 'BGC Group', 'https://www.linkedin.com/jobs/view/4322007517', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Python Developer', 'Genpact', 'https://www.linkedin.com/jobs/view/4339692843', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer Internship | Frontend', 'Ramp', 'https://www.linkedin.com/jobs/view/4336297421', '', '12/4/2025', '5', 'Frontend Challenge Assessment', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Intern, Information Technology', 'Constellation Brands', 'https://www.linkedin.com/jobs/view/4311733547', 'https://cbrands.wd5.myworkdayjobs.com/en-US/CBI_External_Careers/userHome', '12/4/2025', '5', 'Online Assessment', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Junior Web Developer (US)', 'Jobgether', 'https://www.linkedin.com/jobs/view/4314336798', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Python Developer', 'BeaconFire Inc.', 'https://www.linkedin.com/jobs/view/4316262395', '', '12/4/2025', '5', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Technology Summer Internship Program', 'Cantor Fitzgerald', 'https://www.linkedin.com/jobs/view/4321827874', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Information Technology 2026 Summer Intern', 'Loop Capital', 'https://www.linkedin.com/jobs/view/4289382427', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer Intern', 'Greek Learners', 'https://www.linkedin.com/jobs/view/4348479822', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Cyber Security Intern', 'Hireshire', 'https://www.linkedin.com/jobs/view/4348465829', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Cyber Security Intern', 'SalesPilot 365 | CRM', 'https://www.linkedin.com/jobs/view/4348512787', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('DevOps Engineering Intern', 'SalesPilot 365 | CRM', 'https://www.linkedin.com/jobs/view/4348476975', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Junior Software Engineer (Fresh Graduates)', 'Clarvos', 'https://www.linkedin.com/jobs/view/4348455050', '', '12/5/2025', '4', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Java Full Stack Developer', 'Centraprise', 'https://www.linkedin.com/jobs/view/4325830923', '', '12/6/2025', '3', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software & Data Analyst Intern', 'Munich Airport NJ LLC', 'https://www.linkedin.com/jobs/view/4342343871', '', '12/6/2025', '3', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('2026 Internship, Spring - IT', 'RedBull', 'https://www.linkedin.com/jobs/view/4335846414', '', '12/6/2025', '3', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Java Developer', 'Incedo Inc.', 'https://www.linkedin.com/jobs/view/4337180870', '', '12/6/2025', '3', 'Viewed', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Front-End Developer', 'InfoTrack US', 'https://www.linkedin.com/jobs/view/4323604676', '', '12/6/2025', '3', 'EEO Survey', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Engineer', 'Nmble Hiring Solutions', 'https://www.linkedin.com/jobs/view/4336949840', '', '12/6/2025', '3', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Back End Developer', 'SPECTRAFORCE', 'https://www.linkedin.com/jobs/view/4339110699', '', '12/6/2025', '3', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Web Developer', 'CareerUS Solutions', 'https://www.linkedin.com/jobs/view/4347616508', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Junior Full Stack Developer', 'The Gradient Group', 'https://www.linkedin.com/jobs/view/4323493551', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Information Technology (IT) Internship (Summer 2026)', 'MacLean-Fogg', 'https://www.linkedin.com/jobs/view/4301065769', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Java Backend Developer', 'The Dignify Solutions, LLC', 'https://www.linkedin.com/jobs/view/4341885642', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer - Applications (NYC)', 'LinkedIn', 'https://www.linkedin.com/jobs/view/4317506689', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Back End Developer', 'Stellar Consulting Solutions, LLC', 'https://www.linkedin.com/jobs/view/4325664273', '', '12/7/2025', '2', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer - Internship', 'SeatGeek', 'https://www.linkedin.com/jobs/view/4307571879', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Summer Associate - Information Technology', 'Five Star Bank', 'https://www.linkedin.com/jobs/view/4299602794', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer', 'Searchibility', 'https://www.linkedin.com/jobs/view/4340326360', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer', 'Acceler8 Talent', 'https://www.linkedin.com/jobs/view/4341887816', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Python Developer', 'Triangle Services, Inc.', 'https://www.linkedin.com/jobs/view/4336690579', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Core Java Developer', 'Aegistech', 'https://www.linkedin.com/jobs/view/4338426164', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Engineer', 'EC1 Partner', 'https://www.linkedin.com/jobs/view/4348476990', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer', 'Durlston Partners', 'https://www.linkedin.com/jobs/view/4347794307', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Python Developer', 'PRI Technology', 'https://www.linkedin.com/jobs/view/4341781776', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Engineer', 'Tact', 'https://www.linkedin.com/jobs/view/4339440560', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineer', 'Yext', 'https://www.linkedin.com/jobs/view/4081518713', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Engineer', 'Marvis Tire', 'https://www.linkedin.com/jobs/view/4325852192', '', '12/8/2025', '1', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Software Engineering Intern (AI x HealthTech)', 'Ubie', 'https://www.linkedin.com/jobs/view/4326228310', '', '12/9/2025', '0', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Junior / Intern Full-Stack Developer', 'NextGen Coding Company', 'https://www.linkedin.com/jobs/view/4342605950', '', '12/9/2025', '0', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Junior Fullstack & AL ML Software Intern', 'Amptier Inc', 'https://www.linkedin.com/jobs/view/4348757743', '', '12/9/2025', '0', 'Under Review', 'NA', 'NA');
INSERT INTO `applications` (`title`, `company`, `summary`, `application_link`, `date_sent`, `elapsed_time`, `status`, `interview_status`, `email`) VALUES ('Full Stack Intern', 'Sparrow', 'https://www.linkedin.com/jobs/view/4326270979', '', '12/9/2025', '0', 'Under Review', 'NA', 'NA');